name: docs_bmstu
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Install requirements sphinx
        run: |
          python3 -m pip install --upgrade pip
          pip install sphinx==8.2.3 sphinx-autodoc-typehints sphinx_rtd_theme pydantic==2.12.0
      - name: Run sphinx build
        run: |
          sphinx-apidoc -o docs_src/source/ students_folder
          sphinx-build docs_src/source/ docs/_build
          touch docs/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
          allow_empty_commit: true
          force_orphan: true
          keep_files: false
